ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_m/sensor/io
obj-$(CONFIG_OIS_CALIBRATION) += lc898123AXD_htc.o lc898123AXD_md5.o
